# Generated by Django 5.2.14 on 2026-05-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short line under the hero title, e.g. Comunidad Python en RD.', max_length=255),
        ),
    ]
